# Generated by Django 4.2 on 2025-05-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='鲜花名称')),
                ('stock', models.IntegerField(default=1000, verbose_name='鲜花库存量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image', models.TextField(default='', max_length=65535, verbose_name='图片地址')),
                ('flower_language', models.CharField(max_length=255, verbose_name='花语')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='鲜花新增时间')),
            ],
            options={
                'db_table': 'db_flower',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('quantity', models.IntegerField(default=0, verbose_name='购买数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('order_status', models.IntegerField(choices=[(1, '待审核'), (2, '已完成')], default=2, verbose_name='订单状态')),
                ('order_num', models.CharField(default='', max_length=255, verbose_name='订单号')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flower', verbose_name='鲜花id')),
            ],
            options={
                'db_table': 'db_order',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1, verbose_name='角色')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('avatar', models.CharField(default='', max_length=1000, verbose_name='头像')),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='手机号')),
                ('addr', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户新增时间')),
            ],
            options={
                'db_table': 'db_userinfo',
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_review_time', models.DateTimeField(auto_now_add=True, verbose_name='订单审核时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order', verbose_name='订单id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户id')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户id'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=1000, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户id')),
            ],
            options={
                'db_table': 'db_banner',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('content', models.CharField(max_length=1000, verbose_name='公告内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户id')),
            ],
            options={
                'db_table': 'db_announcement',
            },
        ),
    ]
