# Generated by Django 4.2 on 2025-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.TextField(default='', max_length=4294967295, verbose_name='图片地址'),
        ),
    ]
