# Generated by Django 4.2 on 2025-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.TextField(default='', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.TextField(default='', verbose_name='图片地址'),
        ),
    ]
